[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "macapptree"
version = "0.0.1"
dependencies = [
    "atomacos==3.3.0",
    "ollama==0.1.6",
    "pytest==7.4.4",
    "pyobjc==10.3.1",
    "unidecode==1.3.8"
]
requires-python = ">=3.10"
